before_script:
  - export LANG=en_US.UTF-8

before_install:
  - export LANG=en_US.UTF-8
  - gem install cocoapods -v '0.32.1'
  
language: objective-c
xcode_workspace: "JMRI Framework.xcworkspace"
xcode_scheme: libJMRI
